### ISSUE TITLE
Websocket connection between PyMongo Collection and plotly-dash

### ISSUE THREAD

**Issue by diliprk** [marirs/quart-motor#3]
Greetings @marirs  
I am trying to build a `plotly-dash` app that interfaces with a MongoDB collection where data is continuously written at asynchronous time intervals.  I followed this [tutorial](https://www.mongodb.com/developer/products/mongodb/subscribing-changes-browser-websockets/) to set up WebSockets with MongoDB, and this is the output I get.
https://cdn.discordapp.com/attachments/931545568931631194/983232389763448852/unknown.png .

The dash app needs to plot the `equity` field on the y-axis and `time` on the x-axis.
But I don't know how to connect this WebSocket to [Dash](https://www.dash-extensions.com/components/websocket ). Will your `quart-motor` python package be of any help for my requirement? 
Would be grateful for any guidance on this issue, as information on the internet to set up a WebSocket connection between MongoDB and Dash is very scarce?
I am also willing to contribute my code for a demo article or tutorial which can be published in medium or in your website so that future users can refer to the same should a similar requirement arise in the future for other users?

Looking forward to your reply.

Best Regards,
Dilip

**Comment by marirs** [comment]
this is for a framework named `Quart`

**Comment by diliprk** [comment]
I meant to ask can we use your `quart-motor` API to establish a websocket connection with a MongoDB collection and thereafter connect the websocket a plotly-dash line chart?
